// @ts-check
// Every text that the configurator page shows, in English, in Spanish (Spain), and in Catalan. Keys that start with "field." and
// "enum." follow the property paths and the enum values of contracts/game-config.schema.json, and a test fails when
// one of them is missing in a language. Placeholders such as {fileName} are filled by translate().

(function registerUiText() {
  /** @type {readonly MysteryForgeUiLanguage[]} */
  const UI_LANGUAGES = ['en', 'es', 'ca'];

  /**
   * The like / neutral / avoid texts of one puzzle category. All six categories share the same three choices.
   * @param {string} category
   * @param {[string, string, string, string, string, string]} texts
   * @returns {Record<string, string>}
   */
  function preferenceChoices(category, texts) {
    const prefix = `enum.puzzle_preferences.${category}`;
    return {
      [`${prefix}.like.label`]: texts[0],
      [`${prefix}.like.help`]: texts[1],
      [`${prefix}.neutral.label`]: texts[2],
      [`${prefix}.neutral.help`]: texts[3],
      [`${prefix}.avoid.label`]: texts[4],
      [`${prefix}.avoid.help`]: texts[5],
    };
  }

  /** @type {[string, string, string, string, string, string]} */
  const ENGLISH_PREFERENCE = [
    'Love it',
    'Use more of this kind.',
    'Fine',
    'Use a normal amount.',
    'Skip',
    'Leave this kind out.',
  ];
  /** @type {[string, string, string, string, string, string]} */
  const SPANISH_PREFERENCE = [
    'Me encanta',
    'Más de este tipo.',
    'Normal',
    'Una cantidad normal.',
    'Mejor no',
    'Sin este tipo.',
  ];
  /** @type {[string, string, string, string, string, string]} */
  const CATALAN_PREFERENCE = [
    'M’encanta',
    'Més d’aquest tipus.',
    'Normal',
    'Una quantitat normal.',
    'Millor no',
    'Sense aquest tipus.',
  ];

  /** @type {Record<string, string>} */
  const en = {
    'page.title': 'Mystery Forge',
    'page.tagline':
      'Design a printable mystery game for your table. Your AI agent writes it, you print it, and everyone plays.',
    'page.ui_language': 'Page language',
    'page.kicker': 'Case file No. 001',
    'summary.stamp': 'Confidential',
    'page.offline': 'This page works offline. Your choices stay on this computer.',
    'how.title': 'How it works',
    'how.step1.title': 'Configure',
    'how.step1.text': 'Choose who plays and what they enjoy. It takes about five minutes.',
    'how.step2.title': 'Generate with your AI agent',
    'how.step2.text': 'The agent writes the story and checks every puzzle.',
    'how.step3.title': 'Print and play',
    'how.step3.text': 'Print the pages, fill the envelopes, and open the case.',

    'section.players.title': 'Who is playing',
    'section.players.intro': 'Pick a group and we fill in sensible choices. You can change any of them later.',
    'section.game.title': 'The game',
    'section.game.intro': 'How the game feels, how long it lasts, and how hard it is.',
    'section.story.title': 'The story',
    'section.story.intro': 'Give the agent an idea, or let it surprise you.',
    'section.personal.title': 'Make it personal',
    'section.personal.intro': 'Optional touches that turn a good game into your game.',
    'section.puzzles.title': 'Puzzles you like',
    'section.puzzles.intro': 'Tell the agent which kinds of puzzles to use more, and which to skip.',
    'section.printing.title': 'Printing',
    'section.printing.intro': 'What you have at home to print and build the game.',
    'section.look.title': 'Look',
    'section.look.intro': 'The style of the printed pages.',
    'section.help.title': 'Help during the game',
    'section.help.intro': 'Ways for the players to get unstuck without spoilers.',
    'section.generation.title': 'Generation',
    'section.generation.intro': 'How the agent works while it builds your game.',
    'section.advanced.title': 'For experts',

    'form.optional': 'Optional',
    'form.decrease': 'Fewer',
    'form.increase': 'More',
    'form.add': 'Add',
    'form.remove': 'Remove {item}',
    'form.list_full': 'The list is full: {max} at most.',
    'form.list_count': '{count} of {max}',
    'form.text_count': '{count} of {max} characters',
    'form.surprise': 'Leave it empty and the agent invents a surprise story for you.',

    'field.players.names.placeholder': 'Type a name and press Enter',
    'field.theme.idea.placeholder':
      'For example: a stolen painting at a seaside hotel, a missing cake at grandma’s birthday, or a ghost in the school library.',
    'field.personalization.host_name.placeholder': 'For example: Aunt Laura',
    'field.personalization.place.placeholder': 'For example: our cabin by the lake',
    'field.personalization.inside_jokes.placeholder': 'For example: the cat who hates Mondays',
    'field.personalization.dedication.placeholder': 'For example: Happy 40th birthday, Sam!',
    'field.output.folder.placeholder': 'Empty means your Desktop',

    'summary.title': 'Your game',
    'summary.note': 'Estimates. The agent adjusts them to the story.',
    'summary.bar': '{puzzles} puzzles · {time}',
    'estimate.puzzles': 'Puzzles',
    'estimate.envelopes': 'Envelopes',
    'estimate.chapters': 'Chapters',
    'estimate.pages': 'Printed pages',
    'estimate.play_time': 'Play time',
    'estimate.generation': 'Generation time',
    'estimate.about': 'about {time}',
    'warnings.title': 'Worth a look',
    'warnings.none': 'Everything fits together.',
    'warnings.show': 'Show me',

    'warning.kids_death':
      'The game is for kids, but a death is allowed in the story. Turn off "A death in the story" for a gentler plot.',
    'warning.kids_spooky':
      'The game is for kids, but the scary level is "Spooky". "None" or "A little" suits kids better.',
    'warning.solo_game_master':
      'One player with a game master means nobody else plays. Choose "The game runs itself" or "The host plays too".',
    'warning.colors_go_gray': 'The "Kids" style uses bright colors. On a black and white printer they turn gray.',
    'warning.crafts_without_scissors': 'You like craft puzzles, but scissors are off. Most craft puzzles need cutting.',
    'warning.no_scissors': 'Without scissors the agent has fewer kinds of puzzles to choose from.',
    'warning.short_expert':
      'Expert puzzles in a very short game leave room for only a few puzzles. Try a longer game or an easier level.',
    'warning.many_players_no_game_master':
      'More than 8 players is a big group. A game master helps to keep everyone on track.',
    'warning.envelopes_without_envelopes':
      'The game uses envelopes, but you have none. You can fold paper and close it with a sticker.',
    'warning.no_help': 'There are no hints and no answer checks. Players who get stuck cannot get help.',
    'warning.all_puzzles_avoided':
      'You skip every kind of puzzle. The agent then uses its own choice. Mark at least one kind as "Fine".',
    'warning.more_names_than_players': 'You gave more names than players. The agent uses the first {count} names.',

    'action.download': 'Download config',
    'action.load': 'Load config',
    'action.copy_prompt': 'Copy prompt',
    'action.reset': 'Reset',
    'action.undo': 'Undo',
    'action.show_summary': 'Review and save',
    'load.hint': 'You can also drop a .mystery-config.json file anywhere on the page.',
    'drop.title': 'Drop your config file here',

    'status.downloaded': 'Saved {fileName}. Look in your Downloads folder.',
    'status.copied': 'Prompt copied. Paste it into your agent.',
    'status.copy_failed': 'Copy did not work here. Select the text in the box below and copy it.',
    'status.loaded': 'Loaded {fileName}.',
    'status.load_failed': '{fileName} is not a valid Mystery Forge config. Nothing changed.',
    'status.reset': 'All choices are back to the start.',
    'status.draft_restored': 'Your last draft is back.',
    'status.preset_applied': 'Set up for {audience}. You can change any choice below.',
    'note.language_followed':
      'The game follows the page language. Game language: {language}. Paper: {paper}. You can change both below.',

    'error.json': 'The file is not valid JSON text.',
    'error.whole_file': 'The file',
    'error.required': '{field}: this value is missing.',
    'error.additionalProperties': '{field}: this setting is unknown.',
    'error.type': '{field}: the value has the wrong type.',
    'error.enum': '{field}: this choice is not allowed.',
    'error.minimum': '{field}: the value must be {limit} or more.',
    'error.maximum': '{field}: the value must be {limit} or less.',
    'error.maxLength': '{field}: the text must have {limit} characters or fewer.',
    'error.maxItems': '{field}: the list must have {limit} items or fewer.',

    'prompt.title': 'Other agent apps',
    'prompt.help': 'Do you use another agent app instead of Claude Code? Copy this prompt and paste it there.',
    'prompt.intro': 'Create a printable mystery game with Mystery Forge.',
    'prompt.run_skill':
      'Run the create-game skill with the config below. Treat it as the config file {fileName}. Do not change it.',
    'prompt.questions': 'Ask me only the questions that the skill asks.',

    'next.title': 'Next steps',
    'next.install':
      'Install uv (a small tool that runs Python programs) and Claude Code (the AI agent that writes the game). You do this only once.',
    'next.link_uv': 'Install uv',
    'next.link_claude': 'Install Claude Code',
    'next.open': 'Open the "generator" folder of this project in Claude Code:',
    'next.windows_label': 'Windows:',
    'next.windows':
      'in File Explorer, open the folder. Type cmd in the address bar and press Enter. Then type claude and press Enter.',
    'next.mac_label': 'macOS:',
    'next.mac':
      'in Finder, right-click the folder and choose New Terminal at Folder (under Services). Then type claude and press Enter.',
    'next.trust': 'When Claude Code asks if you trust the folder, say yes.',
    'next.say': 'Type "create a game". The agent finds {fileName} in your Downloads folder.',
    'next.note':
      'The run takes {time}. Stay for the first questions. Once you pick the story concept, you can walk away.',

    'field.schema_version.label': 'Config version',
    'field.schema_version.help': 'The version of the config format. The page sets it for you.',
    'enum.schema_version.1.label': 'Version 1',
    'enum.schema_version.1.help': 'The current config format.',

    'field.audience.label': 'Group',
    'field.audience.help': 'Who sits at the table. The group sets the difficulty, the reading load, and the mood.',
    'enum.audience.kids.label': 'Kids',
    'enum.audience.kids.help': 'Ages 7 to 11. Short texts, gentle story, big letters.',
    'enum.audience.family.label': 'Family',
    'enum.audience.family.help': 'Kids and grown-ups together. Fun for every age.',
    'enum.audience.teens.label': 'Teens',
    'enum.audience.teens.help': 'Ages 12 to 17. More mystery and a bit more challenge.',
    'enum.audience.adults.label': 'Adults',
    'enum.audience.adults.help': 'A dinner party or a game night. Darker plots allowed.',
    'enum.audience.puzzle_fans.label': 'Puzzle fans',
    'enum.audience.puzzle_fans.help': 'People who love escape rooms. Hard puzzles, less story.',

    'field.format.label': 'Format',
    'field.format.help': 'How the players move through the game.',
    'enum.format.envelopes.label': 'Open envelopes one by one',
    'enum.format.envelopes.help': 'Each solved puzzle tells you which envelope to open next.',
    'enum.format.case_file.label': 'Read a case file and accuse a suspect',
    'enum.format.case_file.help': 'Study the clues, find the culprit, and prove it.',
    'enum.format.both.label': 'Both (recommended)',
    'enum.format.both.help': 'Envelopes reveal the case file step by step. The richest experience.',

    'field.players.label': 'Players',
    'field.players.help': 'The people who play.',
    'field.players.count.label': 'Number of players',
    'field.players.count.help': 'From 1 to 12. More players means more puzzles at the same time.',
    'field.players.names.label': 'Player names',
    'field.players.names.help': 'The agent can put the names on character cards and in the story.',

    'field.host.label': 'Who runs the game',
    'field.host.help': 'The host is the person who prints and prepares the game.',
    'enum.host.self_running.label': 'The game runs itself',
    'enum.host.self_running.help': 'Everyone plays. The pages tell you what to do next.',
    'enum.host.host_plays.label': 'The host plays too',
    'enum.host.host_plays.help': 'The host sets up the table and then plays like everyone else.',
    'enum.host.game_master.label': 'A game master leads',
    'enum.host.game_master.help': 'The host knows the solution, reads the story aloud, and gives hints.',

    'field.duration_minutes.label': 'Play time',
    'field.duration_minutes.help': 'How long the game lasts at the table, from 30 minutes to 4 hours.',

    'field.difficulty.label': 'Difficulty',
    'field.difficulty.help': 'How hard the puzzles are.',
    'enum.difficulty.easy.label': 'Easy',
    'enum.difficulty.easy.help': 'Clear clues. Good for first-time players.',
    'enum.difficulty.medium.label': 'Medium',
    'enum.difficulty.medium.help': 'Some thinking needed. Good for most groups.',
    'enum.difficulty.hard.label': 'Hard',
    'enum.difficulty.hard.help': 'Clues hide well. For groups that play often.',
    'enum.difficulty.expert.label': 'Expert',
    'enum.difficulty.expert.help': 'Few clues and many steps. For real puzzle lovers.',

    'field.language.label': 'Language of the game',
    'field.language.help': 'The language of every printed page.',
    'enum.language.en.label': 'English',
    'enum.language.en.help': 'All pages in English.',
    'enum.language.es.label': 'Spanish',
    'enum.language.es.help': 'All pages in Spanish.',
    'enum.language.ca.label': 'Catalan',
    'enum.language.ca.help': 'All pages in Catalan.',
    'enum.language.fr.label': 'French',
    'enum.language.fr.help': 'All pages in French.',
    'enum.language.de.label': 'German',
    'enum.language.de.help': 'All pages in German.',
    'enum.language.it.label': 'Italian',
    'enum.language.it.help': 'All pages in Italian.',
    'enum.language.pt.label': 'Portuguese',
    'enum.language.pt.help': 'All pages in Portuguese.',
    'enum.language.af.label': 'Afrikaans',
    'enum.language.af.help': 'All pages in Afrikaans.',
    'enum.language.ar.label': 'Arabic',
    'enum.language.ar.help': 'All pages in Arabic.',
    'enum.language.bg.label': 'Bulgarian',
    'enum.language.bg.help': 'All pages in Bulgarian.',
    'enum.language.bn.label': 'Bengali',
    'enum.language.bn.help': 'All pages in Bengali.',
    'enum.language.cs.label': 'Czech',
    'enum.language.cs.help': 'All pages in Czech.',
    'enum.language.cy.label': 'Welsh',
    'enum.language.cy.help': 'All pages in Welsh.',
    'enum.language.da.label': 'Danish',
    'enum.language.da.help': 'All pages in Danish.',
    'enum.language.el.label': 'Greek',
    'enum.language.el.help': 'All pages in Greek.',
    'enum.language.et.label': 'Estonian',
    'enum.language.et.help': 'All pages in Estonian.',
    'enum.language.eu.label': 'Basque',
    'enum.language.eu.help': 'All pages in Basque.',
    'enum.language.fa.label': 'Persian',
    'enum.language.fa.help': 'All pages in Persian.',
    'enum.language.fi.label': 'Finnish',
    'enum.language.fi.help': 'All pages in Finnish.',
    'enum.language.ga.label': 'Irish',
    'enum.language.ga.help': 'All pages in Irish.',
    'enum.language.gl.label': 'Galician',
    'enum.language.gl.help': 'All pages in Galician.',
    'enum.language.he.label': 'Hebrew',
    'enum.language.he.help': 'All pages in Hebrew.',
    'enum.language.hi.label': 'Hindi',
    'enum.language.hi.help': 'All pages in Hindi.',
    'enum.language.hr.label': 'Croatian',
    'enum.language.hr.help': 'All pages in Croatian.',
    'enum.language.hu.label': 'Hungarian',
    'enum.language.hu.help': 'All pages in Hungarian.',
    'enum.language.id.label': 'Indonesian',
    'enum.language.id.help': 'All pages in Indonesian.',
    'enum.language.is.label': 'Icelandic',
    'enum.language.is.help': 'All pages in Icelandic.',
    'enum.language.ja.label': 'Japanese',
    'enum.language.ja.help': 'All pages in Japanese.',
    'enum.language.ko.label': 'Korean',
    'enum.language.ko.help': 'All pages in Korean.',
    'enum.language.lt.label': 'Lithuanian',
    'enum.language.lt.help': 'All pages in Lithuanian.',
    'enum.language.lv.label': 'Latvian',
    'enum.language.lv.help': 'All pages in Latvian.',
    'enum.language.ms.label': 'Malay',
    'enum.language.ms.help': 'All pages in Malay.',
    'enum.language.nb.label': 'Norwegian',
    'enum.language.nb.help': 'All pages in Norwegian.',
    'enum.language.nl.label': 'Dutch',
    'enum.language.nl.help': 'All pages in Dutch.',
    'enum.language.pl.label': 'Polish',
    'enum.language.pl.help': 'All pages in Polish.',
    'enum.language.ro.label': 'Romanian',
    'enum.language.ro.help': 'All pages in Romanian.',
    'enum.language.ru.label': 'Russian',
    'enum.language.ru.help': 'All pages in Russian.',
    'enum.language.sk.label': 'Slovak',
    'enum.language.sk.help': 'All pages in Slovak.',
    'enum.language.sl.label': 'Slovenian',
    'enum.language.sl.help': 'All pages in Slovenian.',
    'enum.language.sr.label': 'Serbian',
    'enum.language.sr.help': 'All pages in Serbian.',
    'enum.language.sv.label': 'Swedish',
    'enum.language.sv.help': 'All pages in Swedish.',
    'enum.language.sw.label': 'Swahili',
    'enum.language.sw.help': 'All pages in Swahili.',
    'enum.language.ta.label': 'Tamil',
    'enum.language.ta.help': 'All pages in Tamil.',
    'enum.language.th.label': 'Thai',
    'enum.language.th.help': 'All pages in Thai.',
    'enum.language.tl.label': 'Filipino',
    'enum.language.tl.help': 'All pages in Filipino.',
    'enum.language.tr.label': 'Turkish',
    'enum.language.tr.help': 'All pages in Turkish.',
    'enum.language.uk.label': 'Ukrainian',
    'enum.language.uk.help': 'All pages in Ukrainian.',
    'enum.language.ur.label': 'Urdu',
    'enum.language.ur.help': 'All pages in Urdu.',
    'enum.language.vi.label': 'Vietnamese',
    'enum.language.vi.help': 'All pages in Vietnamese.',
    'enum.language.zh.label': 'Chinese',
    'enum.language.zh.help': 'All pages in Chinese.',

    'field.theme.label': 'Story',
    'field.theme.help': 'The story idea and its mood.',
    'field.theme.idea.label': 'Story idea',
    'field.theme.idea.help': 'A few words or a few lines. Places, characters, and a crime all help.',
    'field.theme.tone.label': 'Mood',
    'field.theme.tone.help': 'How the story feels.',
    'enum.theme.tone.surprise.label': 'Surprise me',
    'enum.theme.tone.surprise.help': 'The agent picks the mood that fits the idea.',
    'enum.theme.tone.cozy.label': 'Cozy',
    'enum.theme.tone.cozy.help': 'Warm and light, like a village mystery.',
    'enum.theme.tone.adventure.label': 'Adventure',
    'enum.theme.tone.adventure.help': 'Maps, treasure, and a race against time.',
    'enum.theme.tone.noir.label': 'Noir',
    'enum.theme.tone.noir.help': 'Rainy streets, secrets, and a tired detective.',
    'enum.theme.tone.spooky.label': 'Spooky',
    'enum.theme.tone.spooky.help': 'Creaky doors and strange shadows.',
    'enum.theme.tone.comedic.label': 'Funny',
    'enum.theme.tone.comedic.help': 'Silly suspects and plenty of jokes.',
    'enum.theme.tone.dramatic.label': 'Dramatic',
    'enum.theme.tone.dramatic.help': 'High stakes, betrayal, and big reveals.',
    'field.theme.era.label': 'Time period',
    'field.theme.era.help': 'When the story happens.',
    'enum.theme.era.any.label': 'Any',
    'enum.theme.era.any.help': 'The agent picks the time that fits the idea.',
    'enum.theme.era.historical.label': 'The past',
    'enum.theme.era.historical.help': 'Castles, steam trains, or the roaring twenties.',
    'enum.theme.era.modern.label': 'Today',
    'enum.theme.era.modern.help': 'Phones, offices, and modern cities.',
    'enum.theme.era.future.label': 'The future',
    'enum.theme.era.future.help': 'Space stations, robots, and new technology.',
    'enum.theme.era.fantasy.label': 'Fantasy',
    'enum.theme.era.fantasy.help': 'Magic, dragons, and invented worlds.',

    'field.content.label': 'Content',
    'field.content.help': 'Limits on what the story may contain.',
    'field.content.death_allowed.label': 'A death in the story',
    'field.content.death_allowed.help': 'On allows a classic murder mystery. Off keeps the crime to theft or a puzzle.',
    'field.content.scary_level.label': 'Scary level',
    'field.content.scary_level.help': 'How scary the story may get.',
    'enum.content.scary_level.none.label': 'None',
    'enum.content.scary_level.none.help': 'Nothing scary at all.',
    'enum.content.scary_level.mild.label': 'A little',
    'enum.content.scary_level.mild.help': 'A shiver here and there.',
    'enum.content.scary_level.spooky.label': 'Spooky',
    'enum.content.scary_level.spooky.help': 'A proper ghost story mood.',
    'field.content.reading_load.label': 'Reading',
    'field.content.reading_load.help': 'How much text the players read.',
    'enum.content.reading_load.light.label': 'Light',
    'enum.content.reading_load.light.help': 'Short texts. Good for kids and big groups.',
    'enum.content.reading_load.medium.label': 'Medium',
    'enum.content.reading_load.medium.help': 'Letters and notes of a page or so.',
    'enum.content.reading_load.heavy.label': 'Rich',
    'enum.content.reading_load.heavy.help': 'Diaries, reports, and long letters full of clues.',

    'field.personalization.label': 'Personal touches',
    'field.personalization.help': 'Personal touches that the story includes.',
    'field.personalization.host_name.label': 'Host name',
    'field.personalization.host_name.help': 'The story can mention the host by name.',
    'field.personalization.place.label': 'Place',
    'field.personalization.place.help': 'Where you play. The story can happen there.',
    'field.personalization.inside_jokes.label': 'Inside jokes',
    'field.personalization.inside_jokes.help': 'Short jokes or references that your group knows. Up to 5.',
    'field.personalization.dedication.label': 'Dedication',
    'field.personalization.dedication.help': 'A line for the cover, for example for a birthday.',

    'field.puzzle_preferences.label': 'Puzzle kinds',
    'field.puzzle_preferences.help': 'How much the players like each kind of puzzle.',
    'field.puzzle_preferences.words.label': 'Words',
    'field.puzzle_preferences.words.help': 'Anagrams, ciphers, and hidden messages.',
    'field.puzzle_preferences.numbers.label': 'Numbers',
    'field.puzzle_preferences.numbers.help': 'Lock codes, sums, and dates.',
    'field.puzzle_preferences.logic.label': 'Logic',
    'field.puzzle_preferences.logic.help': 'Grids of clues: who sat where, who owns what.',
    'field.puzzle_preferences.visual.label': 'Visual',
    'field.puzzle_preferences.visual.help': 'Hidden details in pictures, maps, and symbols.',
    'field.puzzle_preferences.crafts.label': 'Crafts',
    'field.puzzle_preferences.crafts.help': 'Fold, cut, and hold pages up to the light.',
    'field.puzzle_preferences.deduction.label': 'Deduction',
    'field.puzzle_preferences.deduction.help': 'Find who lies, compare alibis, spot the gap.',
    ...preferenceChoices('words', ENGLISH_PREFERENCE),
    ...preferenceChoices('numbers', ENGLISH_PREFERENCE),
    ...preferenceChoices('logic', ENGLISH_PREFERENCE),
    ...preferenceChoices('visual', ENGLISH_PREFERENCE),
    ...preferenceChoices('crafts', ENGLISH_PREFERENCE),
    ...preferenceChoices('deduction', ENGLISH_PREFERENCE),

    'field.equipment.label': 'Equipment',
    'field.equipment.help': 'What you have to print and build the game.',
    'field.equipment.printer.label': 'Printer',
    'field.equipment.printer.help': 'The agent picks colors that print well on it.',
    'enum.equipment.printer.color.label': 'Color',
    'enum.equipment.printer.color.help': 'Full color pages.',
    'enum.equipment.printer.black_and_white.label': 'Black and white',
    'enum.equipment.printer.black_and_white.help': 'The pages use only black and shades of gray.',
    'field.equipment.ink_saving.label': 'Save ink',
    'field.equipment.ink_saving.help': 'Light backgrounds that use less ink.',
    'field.equipment.paper.label': 'Paper size',
    'field.equipment.paper.help': 'The paper in your printer.',
    'enum.equipment.paper.A4.label': 'A4',
    'enum.equipment.paper.A4.help': 'The usual size in Europe and most of the world.',
    'enum.equipment.paper.Letter.label': 'Letter',
    'enum.equipment.paper.Letter.help': 'The usual size in the United States and Canada.',
    'field.equipment.scissors.label': 'Scissors',
    'field.equipment.scissors.help': 'Players may cut paper.',
    'field.equipment.tape_or_glue.label': 'Tape or glue',
    'field.equipment.tape_or_glue.help': 'Players may stick pieces together.',
    'field.equipment.envelopes.label': 'Envelopes',
    'field.equipment.envelopes.help': 'You have envelopes to hide the next parts of the game.',

    'field.assistance.label': 'Assistance',
    'field.assistance.help': 'Help for the players during the game.',
    'field.assistance.hints.label': 'Hints',
    'field.assistance.hints.help': 'Small nudges for each puzzle, one at a time.',
    'field.assistance.paper_answer_check.label': 'Paper answer check',
    'field.assistance.paper_answer_check.help': 'A printed page where players check an answer without a device.',
    'field.assistance.companion_page.label': 'Companion page',
    'field.assistance.companion_page.help': 'A page for a phone or a computer that checks answers and gives hints.',

    'field.visuals.label': 'Look',
    'field.visuals.help': 'The look of the printed pages.',
    'field.visuals.style.label': 'Style',
    'field.visuals.style.help': 'The colors, fonts, and decorations of the pages.',
    'enum.visuals.style.auto.label': 'Auto',
    'enum.visuals.style.auto.help': 'The agent picks the style that fits the story.',
    'enum.visuals.style.vintage.label': 'Vintage',
    'enum.visuals.style.vintage.help': 'Old paper, typewriter text, and stamps.',
    'enum.visuals.style.noir.label': 'Noir',
    'enum.visuals.style.noir.help': 'Black, white, and a touch of red.',
    'enum.visuals.style.modern.label': 'Modern',
    'enum.visuals.style.modern.help': 'Clean pages, like a police report of today.',
    'enum.visuals.style.victorian.label': 'Victorian',
    'enum.visuals.style.victorian.help': 'Ornate frames and elegant letters.',
    'enum.visuals.style.scifi.label': 'Sci-fi',
    'enum.visuals.style.scifi.help': 'Screens, grids, and glowing colors.',
    'enum.visuals.style.fantasy.label': 'Fantasy',
    'enum.visuals.style.fantasy.help': 'Parchment, runes, and old maps.',
    'enum.visuals.style.kids.label': 'Kids',
    'enum.visuals.style.kids.help': 'Bright colors and round, friendly shapes.',
    'enum.visuals.style.minimal.label': 'Minimal',
    'enum.visuals.style.minimal.help': 'Plain pages that print fast and clean.',
    'field.visuals.images.label': 'Images',
    'field.visuals.images.help': 'Drawings on the pages.',
    'enum.visuals.images.svg.label': 'Drawings',
    'enum.visuals.images.svg.help': 'Simple drawings that the agent makes for the story.',
    'enum.visuals.images.none.label': 'No images',
    'enum.visuals.images.none.help': 'Text only. Faster to make and to print.',
    'field.visuals.readable_font.label': 'Easy-to-read font',
    'field.visuals.readable_font.help': 'A large, plain font. Good for kids and for tired eyes.',

    'field.generation.label': 'Generation',
    'field.generation.help': 'How the agent works.',
    'field.generation.quality.label': 'Quality',
    'field.generation.quality.help': 'Best takes longer, but fewer puzzles come out broken.',
    'enum.generation.quality.fast.label': 'Fast',
    'enum.generation.quality.fast.help': 'Faster, with fewer checks. Good for a quick test.',
    'enum.generation.quality.best.label': 'Best',
    'enum.generation.quality.best.help': 'Fewer broken puzzles: more AI test players try each puzzle.',
    'field.generation.pick_concept.label': 'Story concept',
    'field.generation.pick_concept.help': 'The agent first writes a few story concepts.',
    'enum.generation.pick_concept.ask.label': 'Let me choose',
    'enum.generation.pick_concept.ask.help': 'The agent shows the concepts and you pick one.',
    'enum.generation.pick_concept.agent.label': 'Agent chooses',
    'enum.generation.pick_concept.agent.help': 'The agent picks one. The story stays a surprise for you too.',
    'field.generation.seed.label': 'Seed',
    'field.generation.seed.help': 'A number that makes random choices repeatable. 0 means a new random seed.',

    'field.output.label': 'Output',
    'field.output.help': 'Where the agent saves the finished game.',
    'field.output.folder.label': 'Output folder',
    'field.output.folder.help': 'The folder for the finished game. Empty means your Desktop.',
  };

  /** @type {Record<string, string>} */
  const es = {
    'page.title': 'Mystery Forge',
    'page.tagline':
      'Diseña un juego de misterio para imprimir. Tu agente de IA lo escribe, tú lo imprimes y todos juegan.',
    'page.ui_language': 'Idioma de la página',
    'page.kicker': 'Expediente n.º 001',
    'summary.stamp': 'Confidencial',
    'page.offline': 'Esta página funciona sin conexión. Tus elecciones se quedan en este ordenador.',
    'how.title': 'Cómo funciona',
    'how.step1.title': 'Configura',
    'how.step1.text': 'Elige quién juega y qué le gusta. Se tarda unos cinco minutos.',
    'how.step2.title': 'Genera con tu agente de IA',
    'how.step2.text': 'El agente escribe la historia y comprueba cada enigma.',
    'how.step3.title': 'Imprime y juega',
    'how.step3.text': 'Imprime las páginas, llena los sobres y abre el caso.',

    'section.players.title': 'Quién juega',
    'section.players.intro': 'Elige un grupo y rellenamos opciones adecuadas. Puedes cambiar cualquiera después.',
    'section.game.title': 'El juego',
    'section.game.intro': 'Cómo se juega, cuánto dura y lo difícil que es.',
    'section.story.title': 'La historia',
    'section.story.intro': 'Dale una idea al agente o deja que te sorprenda.',
    'section.personal.title': 'Hazlo personal',
    'section.personal.intro': 'Detalles opcionales que convierten un buen juego en tu juego.',
    'section.puzzles.title': 'Enigmas que os gustan',
    'section.puzzles.intro': 'Dile al agente qué tipos de enigma usar más y cuáles evitar.',
    'section.printing.title': 'Impresión',
    'section.printing.intro': 'Lo que tienes en casa para imprimir y montar el juego.',
    'section.look.title': 'Aspecto',
    'section.look.intro': 'El estilo de las páginas impresas.',
    'section.help.title': 'Ayuda durante el juego',
    'section.help.intro': 'Formas de desatascarse sin destripar nada.',
    'section.generation.title': 'Generación',
    'section.generation.intro': 'Cómo trabaja el agente mientras crea tu juego.',
    'section.advanced.title': 'Para expertos',

    'form.optional': 'Opcional',
    'form.decrease': 'Menos',
    'form.increase': 'Más',
    'form.add': 'Añadir',
    'form.remove': 'Quitar {item}',
    'form.list_full': 'La lista está llena: {max} como máximo.',
    'form.list_count': '{count} de {max}',
    'form.text_count': '{count} de {max} caracteres',
    'form.surprise': 'Déjalo vacío y el agente inventará una historia sorpresa para ti.',

    'field.players.names.placeholder': 'Escribe un nombre y pulsa Intro',
    'field.theme.idea.placeholder':
      'Por ejemplo: un cuadro robado en un hotel junto al mar, la tarta desaparecida del cumpleaños de la abuela o un fantasma en la biblioteca del colegio.',
    'field.personalization.host_name.placeholder': 'Por ejemplo: la tía Laura',
    'field.personalization.place.placeholder': 'Por ejemplo: nuestra casa del pueblo',
    'field.personalization.inside_jokes.placeholder': 'Por ejemplo: el gato que odia los lunes',
    'field.personalization.dedication.placeholder': 'Por ejemplo: ¡Feliz 40 cumpleaños, Sam!',
    'field.output.folder.placeholder': 'Vacío significa tu Escritorio',

    'summary.title': 'Tu juego',
    'summary.note': 'Son estimaciones. El agente las ajusta a la historia.',
    'summary.bar': '{puzzles} enigmas · {time}',
    'estimate.puzzles': 'Enigmas',
    'estimate.envelopes': 'Sobres',
    'estimate.chapters': 'Capítulos',
    'estimate.pages': 'Páginas impresas',
    'estimate.play_time': 'Tiempo de juego',
    'estimate.generation': 'Tiempo de generación',
    'estimate.about': 'aprox. {time}',
    'warnings.title': 'Conviene revisar',
    'warnings.none': 'Todo encaja.',
    'warnings.show': 'Ver',

    'warning.kids_death':
      'El juego es para niños, pero la historia permite una muerte. Desactiva «Una muerte en la historia» para una trama más suave.',
    'warning.kids_spooky':
      'El juego es para niños, pero el nivel de miedo es «Terror». «Nada» o «Un poco» encajan mejor con niños.',
    'warning.solo_game_master':
      'Un jugador con director de juego significa que nadie más juega. Elige «El juego se dirige solo» o «El anfitrión también juega».',
    'warning.colors_go_gray':
      'El estilo «Infantil» usa colores vivos. En una impresora en blanco y negro se ven grises.',
    'warning.crafts_without_scissors':
      'Te gustan los enigmas manuales, pero las tijeras están desactivadas. Casi todos necesitan recortar.',
    'warning.no_scissors': 'Sin tijeras, el agente tiene menos tipos de enigma entre los que elegir.',
    'warning.short_expert':
      'Enigmas de nivel experto en una partida muy corta dejan sitio para muy pocos. Prueba una partida más larga o un nivel más fácil.',
    'warning.many_players_no_game_master':
      'Más de 8 jugadores es un grupo grande. Un director de juego ayuda a que nadie se pierda.',
    'warning.envelopes_without_envelopes':
      'El juego usa sobres, pero no tienes. Puedes doblar un papel y cerrarlo con una pegatina.',
    'warning.no_help': 'No hay pistas ni comprobación de respuestas. Quien se atasque no podrá pedir ayuda.',
    'warning.all_puzzles_avoided':
      'Evitas todos los tipos de enigma. Entonces el agente elige por su cuenta. Marca al menos un tipo como «Normal».',
    'warning.more_names_than_players':
      'Has puesto más nombres que jugadores. El agente usa los {count} primeros nombres.',

    'action.download': 'Descargar configuración',
    'action.load': 'Cargar configuración',
    'action.copy_prompt': 'Copiar instrucción',
    'action.reset': 'Empezar de nuevo',
    'action.undo': 'Deshacer',
    'action.show_summary': 'Revisar y guardar',
    'load.hint': 'También puedes soltar un archivo .mystery-config.json en cualquier parte de la página.',
    'drop.title': 'Suelta aquí tu archivo de configuración',

    'status.downloaded': 'Guardado {fileName}. Búscalo en tu carpeta de Descargas.',
    'status.copied': 'Instrucción copiada. Pégala en tu agente.',
    'status.copy_failed': 'Aquí no se ha podido copiar. Selecciona el texto del cuadro de abajo y cópialo.',
    'status.loaded': 'Cargado {fileName}.',
    'status.load_failed': '{fileName} no es una configuración válida de Mystery Forge. No ha cambiado nada.',
    'status.reset': 'Todas las opciones han vuelto al principio.',
    'status.draft_restored': 'Hemos recuperado tu último borrador.',
    'status.preset_applied': 'Preparado para «{audience}». Puedes cambiar cualquier opción abajo.',
    'note.language_followed':
      'El juego sigue el idioma de la página. Idioma del juego: {language}. Papel: {paper}. Puedes cambiar los dos abajo.',

    'error.json': 'El archivo no contiene un texto JSON válido.',
    'error.whole_file': 'El archivo',
    'error.required': '{field}: falta este valor.',
    'error.additionalProperties': '{field}: este ajuste no existe.',
    'error.type': '{field}: el valor no es del tipo correcto.',
    'error.enum': '{field}: esta opción no está permitida.',
    'error.minimum': '{field}: el valor debe ser {limit} o más.',
    'error.maximum': '{field}: el valor debe ser {limit} o menos.',
    'error.maxLength': '{field}: el texto debe tener {limit} caracteres o menos.',
    'error.maxItems': '{field}: la lista debe tener {limit} elementos o menos.',

    'prompt.title': 'Otras apps de agentes',
    'prompt.help': '¿Usas otra app de agentes en lugar de Claude Code? Copia esta instrucción y pégala allí.',
    'prompt.intro': 'Crea un juego de misterio para imprimir con Mystery Forge.',
    'prompt.run_skill':
      'Ejecuta la skill create-game con la configuración de abajo. Trátala como el archivo de configuración {fileName}. No la cambies.',
    'prompt.questions': 'Pregúntame solo lo que pregunte la skill.',

    'next.title': 'Siguientes pasos',
    'next.install':
      'Instala uv (una pequeña herramienta que ejecuta programas de Python) y Claude Code (el agente de IA que escribe el juego). Solo se hace una vez.',
    'next.link_uv': 'Instalar uv',
    'next.link_claude': 'Instalar Claude Code',
    'next.open': 'Abre la carpeta «generator» de este proyecto en Claude Code:',
    'next.windows_label': 'Windows:',
    'next.windows':
      'en el Explorador de archivos, abre la carpeta. Escribe cmd en la barra de direcciones y pulsa Intro. Después escribe claude y pulsa Intro.',
    'next.mac_label': 'macOS:',
    'next.mac':
      'en el Finder, haz clic derecho en la carpeta y elige «Nuevo terminal en la carpeta» (en Servicios). Después escribe claude y pulsa Intro.',
    'next.trust': 'Cuando Claude Code pregunte si confías en la carpeta, di que sí.',
    'next.say': 'Escribe «crea un juego». El agente encuentra {fileName} en tu carpeta de Descargas.',
    'next.note':
      'El proceso tarda {time}. Quédate para las primeras preguntas. Cuando elijas el concepto de la historia, ya puedes irte.',

    'field.schema_version.label': 'Versión de la configuración',
    'field.schema_version.help': 'La versión del formato de configuración. La página la pone por ti.',
    'enum.schema_version.1.label': 'Versión 1',
    'enum.schema_version.1.help': 'El formato de configuración actual.',

    'field.audience.label': 'Grupo',
    'field.audience.help': 'Quién se sienta a la mesa. El grupo ajusta la dificultad, la lectura y el tono.',
    'enum.audience.kids.label': 'Niños',
    'enum.audience.kids.help': 'De 7 a 11 años. Textos cortos, historia amable y letra grande.',
    'enum.audience.family.label': 'Familia',
    'enum.audience.family.help': 'Pequeños y mayores juntos. Divertido para todas las edades.',
    'enum.audience.teens.label': 'Adolescentes',
    'enum.audience.teens.help': 'De 12 a 17 años. Más misterio y un poco más de reto.',
    'enum.audience.adults.label': 'Adultos',
    'enum.audience.adults.help': 'Una cena con amigos o una noche de juegos. Se permiten tramas más oscuras.',
    'enum.audience.puzzle_fans.label': 'Fans de los enigmas',
    'enum.audience.puzzle_fans.help': 'Gente que adora las salas de escape. Enigmas difíciles y menos historia.',

    'field.format.label': 'Formato',
    'field.format.help': 'Cómo avanzan los jugadores por el juego.',
    'enum.format.envelopes.label': 'Abrir sobres uno a uno',
    'enum.format.envelopes.help': 'Cada enigma resuelto te dice qué sobre abrir después.',
    'enum.format.case_file.label': 'Leer un expediente y acusar a un sospechoso',
    'enum.format.case_file.help': 'Estudia las pistas, encuentra al culpable y demuéstralo.',
    'enum.format.both.label': 'Las dos cosas (recomendado)',
    'enum.format.both.help': 'Los sobres revelan el expediente paso a paso. La experiencia más completa.',

    'field.players.label': 'Jugadores',
    'field.players.help': 'Las personas que juegan.',
    'field.players.count.label': 'Número de jugadores',
    'field.players.count.help': 'De 1 a 12. Con más jugadores hay más enigmas a la vez.',
    'field.players.names.label': 'Nombres de los jugadores',
    'field.players.names.help': 'El agente puede poner los nombres en las fichas de personaje y en la historia.',

    'field.host.label': 'Quién dirige el juego',
    'field.host.help': 'El anfitrión es la persona que imprime y prepara el juego.',
    'enum.host.self_running.label': 'El juego se dirige solo',
    'enum.host.self_running.help': 'Todos juegan. Las páginas os dicen qué hacer después.',
    'enum.host.host_plays.label': 'El anfitrión también juega',
    'enum.host.host_plays.help': 'El anfitrión prepara la mesa y luego juega como los demás.',
    'enum.host.game_master.label': 'Un director de juego',
    'enum.host.game_master.help': 'El anfitrión conoce la solución, lee la historia en voz alta y da pistas.',

    'field.duration_minutes.label': 'Tiempo de juego',
    'field.duration_minutes.help': 'Lo que dura la partida en la mesa, de 30 minutos a 4 horas.',

    'field.difficulty.label': 'Dificultad',
    'field.difficulty.help': 'Lo difíciles que son los enigmas.',
    'enum.difficulty.easy.label': 'Fácil',
    'enum.difficulty.easy.help': 'Pistas claras. Ideal para quien juega por primera vez.',
    'enum.difficulty.medium.label': 'Media',
    'enum.difficulty.medium.help': 'Hay que pensar un poco. Ideal para casi todos los grupos.',
    'enum.difficulty.hard.label': 'Difícil',
    'enum.difficulty.hard.help': 'Las pistas se esconden bien. Para grupos que juegan a menudo.',
    'enum.difficulty.expert.label': 'Experto',
    'enum.difficulty.expert.help': 'Pocas pistas y muchos pasos. Para amantes de los enigmas.',

    'field.language.label': 'Idioma del juego',
    'field.language.help': 'El idioma de todas las páginas impresas.',
    'enum.language.en.label': 'Inglés',
    'enum.language.en.help': 'Todas las páginas en inglés.',
    'enum.language.es.label': 'Español',
    'enum.language.es.help': 'Todas las páginas en español.',
    'enum.language.ca.label': 'Catalán',
    'enum.language.ca.help': 'Todas las páginas en catalán.',
    'enum.language.fr.label': 'Francés',
    'enum.language.fr.help': 'Todas las páginas en francés.',
    'enum.language.de.label': 'Alemán',
    'enum.language.de.help': 'Todas las páginas en alemán.',
    'enum.language.it.label': 'Italiano',
    'enum.language.it.help': 'Todas las páginas en italiano.',
    'enum.language.pt.label': 'Portugués',
    'enum.language.pt.help': 'Todas las páginas en portugués.',
    'enum.language.af.label': 'Afrikáans',
    'enum.language.af.help': 'Todas las páginas en afrikáans.',
    'enum.language.ar.label': 'Árabe',
    'enum.language.ar.help': 'Todas las páginas en árabe.',
    'enum.language.bg.label': 'Búlgaro',
    'enum.language.bg.help': 'Todas las páginas en búlgaro.',
    'enum.language.bn.label': 'Bengalí',
    'enum.language.bn.help': 'Todas las páginas en bengalí.',
    'enum.language.cs.label': 'Checo',
    'enum.language.cs.help': 'Todas las páginas en checo.',
    'enum.language.cy.label': 'Galés',
    'enum.language.cy.help': 'Todas las páginas en galés.',
    'enum.language.da.label': 'Danés',
    'enum.language.da.help': 'Todas las páginas en danés.',
    'enum.language.el.label': 'Griego',
    'enum.language.el.help': 'Todas las páginas en griego.',
    'enum.language.et.label': 'Estonio',
    'enum.language.et.help': 'Todas las páginas en estonio.',
    'enum.language.eu.label': 'Euskera',
    'enum.language.eu.help': 'Todas las páginas en euskera.',
    'enum.language.fa.label': 'Persa',
    'enum.language.fa.help': 'Todas las páginas en persa.',
    'enum.language.fi.label': 'Finés',
    'enum.language.fi.help': 'Todas las páginas en finés.',
    'enum.language.ga.label': 'Irlandés',
    'enum.language.ga.help': 'Todas las páginas en irlandés.',
    'enum.language.gl.label': 'Gallego',
    'enum.language.gl.help': 'Todas las páginas en gallego.',
    'enum.language.he.label': 'Hebreo',
    'enum.language.he.help': 'Todas las páginas en hebreo.',
    'enum.language.hi.label': 'Hindi',
    'enum.language.hi.help': 'Todas las páginas en hindi.',
    'enum.language.hr.label': 'Croata',
    'enum.language.hr.help': 'Todas las páginas en croata.',
    'enum.language.hu.label': 'Húngaro',
    'enum.language.hu.help': 'Todas las páginas en húngaro.',
    'enum.language.id.label': 'Indonesio',
    'enum.language.id.help': 'Todas las páginas en indonesio.',
    'enum.language.is.label': 'Islandés',
    'enum.language.is.help': 'Todas las páginas en islandés.',
    'enum.language.ja.label': 'Japonés',
    'enum.language.ja.help': 'Todas las páginas en japonés.',
    'enum.language.ko.label': 'Coreano',
    'enum.language.ko.help': 'Todas las páginas en coreano.',
    'enum.language.lt.label': 'Lituano',
    'enum.language.lt.help': 'Todas las páginas en lituano.',
    'enum.language.lv.label': 'Letón',
    'enum.language.lv.help': 'Todas las páginas en letón.',
    'enum.language.ms.label': 'Malayo',
    'enum.language.ms.help': 'Todas las páginas en malayo.',
    'enum.language.nb.label': 'Noruego',
    'enum.language.nb.help': 'Todas las páginas en noruego.',
    'enum.language.nl.label': 'Neerlandés',
    'enum.language.nl.help': 'Todas las páginas en neerlandés.',
    'enum.language.pl.label': 'Polaco',
    'enum.language.pl.help': 'Todas las páginas en polaco.',
    'enum.language.ro.label': 'Rumano',
    'enum.language.ro.help': 'Todas las páginas en rumano.',
    'enum.language.ru.label': 'Ruso',
    'enum.language.ru.help': 'Todas las páginas en ruso.',
    'enum.language.sk.label': 'Eslovaco',
    'enum.language.sk.help': 'Todas las páginas en eslovaco.',
    'enum.language.sl.label': 'Esloveno',
    'enum.language.sl.help': 'Todas las páginas en esloveno.',
    'enum.language.sr.label': 'Serbio',
    'enum.language.sr.help': 'Todas las páginas en serbio.',
    'enum.language.sv.label': 'Sueco',
    'enum.language.sv.help': 'Todas las páginas en sueco.',
    'enum.language.sw.label': 'Suajili',
    'enum.language.sw.help': 'Todas las páginas en suajili.',
    'enum.language.ta.label': 'Tamil',
    'enum.language.ta.help': 'Todas las páginas en tamil.',
    'enum.language.th.label': 'Tailandés',
    'enum.language.th.help': 'Todas las páginas en tailandés.',
    'enum.language.tl.label': 'Filipino',
    'enum.language.tl.help': 'Todas las páginas en filipino.',
    'enum.language.tr.label': 'Turco',
    'enum.language.tr.help': 'Todas las páginas en turco.',
    'enum.language.uk.label': 'Ucraniano',
    'enum.language.uk.help': 'Todas las páginas en ucraniano.',
    'enum.language.ur.label': 'Urdu',
    'enum.language.ur.help': 'Todas las páginas en urdu.',
    'enum.language.vi.label': 'Vietnamita',
    'enum.language.vi.help': 'Todas las páginas en vietnamita.',
    'enum.language.zh.label': 'Chino',
    'enum.language.zh.help': 'Todas las páginas en chino.',

    'field.theme.label': 'Historia',
    'field.theme.help': 'La idea de la historia y su tono.',
    'field.theme.idea.label': 'Idea para la historia',
    'field.theme.idea.help': 'Unas palabras o unas líneas. Lugares, personajes y un crimen ayudan mucho.',
    'field.theme.tone.label': 'Tono',
    'field.theme.tone.help': 'Qué sensación transmite la historia.',
    'enum.theme.tone.surprise.label': 'Sorpréndeme',
    'enum.theme.tone.surprise.help': 'El agente elige el tono que encaja con la idea.',
    'enum.theme.tone.cozy.label': 'Acogedor',
    'enum.theme.tone.cozy.help': 'Cálido y ligero, como un misterio de pueblo.',
    'enum.theme.tone.adventure.label': 'Aventura',
    'enum.theme.tone.adventure.help': 'Mapas, tesoros y una carrera contra el reloj.',
    'enum.theme.tone.noir.label': 'Negro',
    'enum.theme.tone.noir.help': 'Calles con lluvia, secretos y un detective cansado.',
    'enum.theme.tone.spooky.label': 'Inquietante',
    'enum.theme.tone.spooky.help': 'Puertas que crujen y sombras extrañas.',
    'enum.theme.tone.comedic.label': 'Divertido',
    'enum.theme.tone.comedic.help': 'Sospechosos absurdos y muchas bromas.',
    'enum.theme.tone.dramatic.label': 'Dramático',
    'enum.theme.tone.dramatic.help': 'Mucho en juego, traiciones y grandes revelaciones.',
    'field.theme.era.label': 'Época',
    'field.theme.era.help': 'Cuándo ocurre la historia.',
    'enum.theme.era.any.label': 'Cualquiera',
    'enum.theme.era.any.help': 'El agente elige la época que encaja con la idea.',
    'enum.theme.era.historical.label': 'El pasado',
    'enum.theme.era.historical.help': 'Castillos, trenes de vapor o los felices años veinte.',
    'enum.theme.era.modern.label': 'Hoy',
    'enum.theme.era.modern.help': 'Móviles, oficinas y ciudades modernas.',
    'enum.theme.era.future.label': 'El futuro',
    'enum.theme.era.future.help': 'Estaciones espaciales, robots y nueva tecnología.',
    'enum.theme.era.fantasy.label': 'Fantasía',
    'enum.theme.era.fantasy.help': 'Magia, dragones y mundos inventados.',

    'field.content.label': 'Contenido',
    'field.content.help': 'Límites sobre lo que puede contener la historia.',
    'field.content.death_allowed.label': 'Una muerte en la historia',
    'field.content.death_allowed.help':
      'Activado permite un asesinato clásico. Desactivado deja el crimen en un robo o un enigma.',
    'field.content.scary_level.label': 'Nivel de miedo',
    'field.content.scary_level.help': 'Cuánto miedo puede dar la historia.',
    'enum.content.scary_level.none.label': 'Nada',
    'enum.content.scary_level.none.help': 'Nada de miedo.',
    'enum.content.scary_level.mild.label': 'Un poco',
    'enum.content.scary_level.mild.help': 'Algún escalofrío de vez en cuando.',
    'enum.content.scary_level.spooky.label': 'Terror',
    'enum.content.scary_level.spooky.help': 'Ambiente de auténtica historia de fantasmas.',
    'field.content.reading_load.label': 'Lectura',
    'field.content.reading_load.help': 'Cuánto texto leen los jugadores.',
    'enum.content.reading_load.light.label': 'Ligera',
    'enum.content.reading_load.light.help': 'Textos cortos. Ideal para niños y grupos grandes.',
    'enum.content.reading_load.medium.label': 'Media',
    'enum.content.reading_load.medium.help': 'Cartas y notas de una página más o menos.',
    'enum.content.reading_load.heavy.label': 'Abundante',
    'enum.content.reading_load.heavy.help': 'Diarios, informes y cartas largas llenas de pistas.',

    'field.personalization.label': 'Toques personales',
    'field.personalization.help': 'Detalles personales que incluye la historia.',
    'field.personalization.host_name.label': 'Nombre del anfitrión',
    'field.personalization.host_name.help': 'La historia puede nombrar al anfitrión.',
    'field.personalization.place.label': 'Lugar',
    'field.personalization.place.help': 'Dónde jugáis. La historia puede ocurrir allí.',
    'field.personalization.inside_jokes.label': 'Bromas internas',
    'field.personalization.inside_jokes.help': 'Bromas o referencias cortas que conoce tu grupo. Hasta 5.',
    'field.personalization.dedication.label': 'Dedicatoria',
    'field.personalization.dedication.help': 'Una línea para la portada, por ejemplo para un cumpleaños.',

    'field.puzzle_preferences.label': 'Tipos de enigma',
    'field.puzzle_preferences.help': 'Cuánto les gusta a los jugadores cada tipo de enigma.',
    'field.puzzle_preferences.words.label': 'Palabras',
    'field.puzzle_preferences.words.help': 'Anagramas, cifrados y mensajes ocultos.',
    'field.puzzle_preferences.numbers.label': 'Números',
    'field.puzzle_preferences.numbers.help': 'Códigos de candado, sumas y fechas.',
    'field.puzzle_preferences.logic.label': 'Lógica',
    'field.puzzle_preferences.logic.help': 'Tablas de pistas: quién se sentó dónde, quién tiene qué.',
    'field.puzzle_preferences.visual.label': 'Visuales',
    'field.puzzle_preferences.visual.help': 'Detalles ocultos en dibujos, mapas y símbolos.',
    'field.puzzle_preferences.crafts.label': 'Manualidades',
    'field.puzzle_preferences.crafts.help': 'Doblar, recortar y mirar páginas a contraluz.',
    'field.puzzle_preferences.deduction.label': 'Deducción',
    'field.puzzle_preferences.deduction.help': 'Descubrir quién miente, comparar coartadas y ver el fallo.',
    ...preferenceChoices('words', SPANISH_PREFERENCE),
    ...preferenceChoices('numbers', SPANISH_PREFERENCE),
    ...preferenceChoices('logic', SPANISH_PREFERENCE),
    ...preferenceChoices('visual', SPANISH_PREFERENCE),
    ...preferenceChoices('crafts', SPANISH_PREFERENCE),
    ...preferenceChoices('deduction', SPANISH_PREFERENCE),

    'field.equipment.label': 'Material',
    'field.equipment.help': 'Lo que tienes para imprimir y montar el juego.',
    'field.equipment.printer.label': 'Impresora',
    'field.equipment.printer.help': 'El agente elige colores que se impriman bien en ella.',
    'enum.equipment.printer.color.label': 'Color',
    'enum.equipment.printer.color.help': 'Páginas a todo color.',
    'enum.equipment.printer.black_and_white.label': 'Blanco y negro',
    'enum.equipment.printer.black_and_white.help': 'Las páginas usan solo negro y tonos de gris.',
    'field.equipment.ink_saving.label': 'Ahorrar tinta',
    'field.equipment.ink_saving.help': 'Fondos claros que gastan menos tinta.',
    'field.equipment.paper.label': 'Tamaño de papel',
    'field.equipment.paper.help': 'El papel de tu impresora.',
    'enum.equipment.paper.A4.label': 'A4',
    'enum.equipment.paper.A4.help': 'El tamaño habitual en Europa y casi todo el mundo.',
    'enum.equipment.paper.Letter.label': 'Carta',
    'enum.equipment.paper.Letter.help': 'El tamaño habitual en Estados Unidos y Canadá.',
    'field.equipment.scissors.label': 'Tijeras',
    'field.equipment.scissors.help': 'Los jugadores pueden recortar papel.',
    'field.equipment.tape_or_glue.label': 'Celo o pegamento',
    'field.equipment.tape_or_glue.help': 'Los jugadores pueden pegar piezas.',
    'field.equipment.envelopes.label': 'Sobres',
    'field.equipment.envelopes.help': 'Tienes sobres para esconder las siguientes partes del juego.',

    'field.assistance.label': 'Ayuda',
    'field.assistance.help': 'Ayuda para los jugadores durante el juego.',
    'field.assistance.hints.label': 'Pistas',
    'field.assistance.hints.help': 'Pequeños empujones para cada enigma, de uno en uno.',
    'field.assistance.paper_answer_check.label': 'Comprobación en papel',
    'field.assistance.paper_answer_check.help': 'Una página impresa para comprobar respuestas sin ningún aparato.',
    'field.assistance.companion_page.label': 'Página de apoyo',
    'field.assistance.companion_page.help':
      'Una página para el móvil o el ordenador que comprueba respuestas y da pistas.',

    'field.visuals.label': 'Aspecto',
    'field.visuals.help': 'El aspecto de las páginas impresas.',
    'field.visuals.style.label': 'Estilo',
    'field.visuals.style.help': 'Los colores, las letras y los adornos de las páginas.',
    'enum.visuals.style.auto.label': 'Automático',
    'enum.visuals.style.auto.help': 'El agente elige el estilo que encaja con la historia.',
    'enum.visuals.style.vintage.label': 'Antiguo',
    'enum.visuals.style.vintage.help': 'Papel viejo, letra de máquina de escribir y sellos.',
    'enum.visuals.style.noir.label': 'Negro',
    'enum.visuals.style.noir.help': 'Blanco, negro y un toque de rojo.',
    'enum.visuals.style.modern.label': 'Moderno',
    'enum.visuals.style.modern.help': 'Páginas limpias, como un informe policial de hoy.',
    'enum.visuals.style.victorian.label': 'Victoriano',
    'enum.visuals.style.victorian.help': 'Marcos recargados y letras elegantes.',
    'enum.visuals.style.scifi.label': 'Ciencia ficción',
    'enum.visuals.style.scifi.help': 'Pantallas, cuadrículas y colores luminosos.',
    'enum.visuals.style.fantasy.label': 'Fantasía',
    'enum.visuals.style.fantasy.help': 'Pergamino, runas y mapas antiguos.',
    'enum.visuals.style.kids.label': 'Infantil',
    'enum.visuals.style.kids.help': 'Colores vivos y formas redondas y amables.',
    'enum.visuals.style.minimal.label': 'Minimalista',
    'enum.visuals.style.minimal.help': 'Páginas sencillas que se imprimen rápido y limpias.',
    'field.visuals.images.label': 'Imágenes',
    'field.visuals.images.help': 'Dibujos en las páginas.',
    'enum.visuals.images.svg.label': 'Dibujos',
    'enum.visuals.images.svg.help': 'Dibujos sencillos que el agente crea para la historia.',
    'enum.visuals.images.none.label': 'Sin imágenes',
    'enum.visuals.images.none.help': 'Solo texto. Más rápido de crear y de imprimir.',
    'field.visuals.readable_font.label': 'Letra fácil de leer',
    'field.visuals.readable_font.help': 'Una letra grande y sencilla. Ideal para niños y para ojos cansados.',

    'field.generation.label': 'Generación',
    'field.generation.help': 'Cómo trabaja el agente.',
    'field.generation.quality.label': 'Calidad',
    'field.generation.quality.help': 'La mejor tarda más, pero salen menos enigmas rotos.',
    'enum.generation.quality.fast.label': 'Rápida',
    'enum.generation.quality.fast.help': 'Más rápida, con menos comprobaciones. Ideal para una prueba rápida.',
    'enum.generation.quality.best.label': 'La mejor',
    'enum.generation.quality.best.help': 'Menos enigmas rotos: más jugadores de prueba con IA intentan cada enigma.',
    'field.generation.pick_concept.label': 'Concepto de la historia',
    'field.generation.pick_concept.help': 'Primero el agente escribe varios conceptos de historia.',
    'enum.generation.pick_concept.ask.label': 'Quiero elegir',
    'enum.generation.pick_concept.ask.help': 'El agente te enseña los conceptos y tú eliges uno.',
    'enum.generation.pick_concept.agent.label': 'Elige el agente',
    'enum.generation.pick_concept.agent.help': 'El agente elige uno. La historia también será una sorpresa para ti.',
    'field.generation.seed.label': 'Semilla',
    'field.generation.seed.help':
      'Un número que hace repetibles las elecciones al azar. 0 significa una semilla nueva.',

    'field.output.label': 'Salida',
    'field.output.help': 'Dónde guarda el agente el juego terminado.',
    'field.output.folder.label': 'Carpeta de salida',
    'field.output.folder.help': 'La carpeta para el juego terminado. Vacío significa tu Escritorio.',
  };

  /** @type {Record<string, string>} */
  const ca = {
    'page.title': 'Mystery Forge',
    'page.tagline':
      'Dissenya un joc de misteri per imprimir. El teu agent d’IA l’escriu, tu l’imprimeixes i tothom hi juga.',
    'page.ui_language': 'Idioma de la pàgina',
    'page.kicker': 'Expedient núm. 001',
    'summary.stamp': 'Confidencial',
    'page.offline': 'Aquesta pàgina funciona sense connexió. Les teves eleccions es queden en aquest ordinador.',
    'how.title': 'Com funciona',
    'how.step1.title': 'Configura',
    'how.step1.text': 'Tria qui juga i què li agrada. Només calen uns cinc minuts.',
    'how.step2.title': 'Genera amb el teu agent d’IA',
    'how.step2.text': 'L’agent escriu la història i comprova cada enigma.',
    'how.step3.title': 'Imprimeix i juga',
    'how.step3.text': 'Imprimeix les pàgines, omple els sobres i obre el cas.',

    'section.players.title': 'Qui juga',
    'section.players.intro': 'Tria un grup i omplim opcions adequades. Pots canviar-ne qualsevol després.',
    'section.game.title': 'El joc',
    'section.game.intro': 'Com es juga, quant dura i quina dificultat té.',
    'section.story.title': 'La història',
    'section.story.intro': 'Dona una idea a l’agent o deixa que et sorprengui.',
    'section.personal.title': 'Fes-lo personal',
    'section.personal.intro': 'Detalls opcionals que converteixen un bon joc en el teu joc.',
    'section.puzzles.title': 'Enigmes que us agraden',
    'section.puzzles.intro': 'Digues a l’agent quins tipus d’enigma ha d’usar més i quins ha d’evitar.',
    'section.printing.title': 'Impressió',
    'section.printing.intro': 'El que tens a casa per imprimir i muntar el joc.',
    'section.look.title': 'Aspecte',
    'section.look.intro': 'L’estil de les pàgines impreses.',
    'section.help.title': 'Ajuda durant el joc',
    'section.help.intro': 'Maneres de desencallar-se sense desvelar res.',
    'section.generation.title': 'Generació',
    'section.generation.intro': 'Com treballa l’agent mentre crea el teu joc.',
    'section.advanced.title': 'Per a experts',

    'form.optional': 'Opcional',
    'form.decrease': 'Menys',
    'form.increase': 'Més',
    'form.add': 'Afegeix',
    'form.remove': 'Treu {item}',
    'form.list_full': 'La llista és plena: {max} com a màxim.',
    'form.list_count': '{count} de {max}',
    'form.text_count': '{count} de {max} caràcters',
    'form.surprise': 'Deixa-ho buit i l’agent s’inventarà una història sorpresa per a tu.',

    'field.players.names.placeholder': 'Escriu un nom i prem Retorn',
    'field.theme.idea.placeholder':
      'Per exemple: un quadre robat en un hotel vora el mar, el pastís desaparegut de l’aniversari de l’àvia o un fantasma a la biblioteca de l’escola.',
    'field.personalization.host_name.placeholder': 'Per exemple: la tieta Laura',
    'field.personalization.place.placeholder': 'Per exemple: la nostra casa del poble',
    'field.personalization.inside_jokes.placeholder': 'Per exemple: el gat que odia els dilluns',
    'field.personalization.dedication.placeholder': 'Per exemple: Per molts anys, Sam! Ja en fas 40!',
    'field.output.folder.placeholder': 'Buit vol dir el teu Escriptori',

    'summary.title': 'El teu joc',
    'summary.note': 'Són estimacions. L’agent les ajusta a la història.',
    'summary.bar': '{puzzles} enigmes · {time}',
    'estimate.puzzles': 'Enigmes',
    'estimate.envelopes': 'Sobres',
    'estimate.chapters': 'Capítols',
    'estimate.pages': 'Pàgines impreses',
    'estimate.play_time': 'Temps de joc',
    'estimate.generation': 'Temps de generació',
    'estimate.about': 'aprox. {time}',
    'warnings.title': 'Convé revisar',
    'warnings.none': 'Tot encaixa.',
    'warnings.show': 'Mostra-ho',

    'warning.kids_death':
      'El joc és per a infants, però la història permet una mort. Desactiva «Una mort a la història» per a una trama més suau.',
    'warning.kids_spooky':
      'El joc és per a infants, però el nivell de por és «Terror». «Gens» o «Una mica» són més adequats per a infants.',
    'warning.solo_game_master':
      'Un jugador amb director de joc vol dir que ningú més no juga. Tria «El joc es dirigeix sol» o «L’amfitrió també juga».',
    'warning.colors_go_gray':
      'L’estil «Infantil» fa servir colors vius. En una impressora en blanc i negre es veuen grisos.',
    'warning.crafts_without_scissors':
      'T’agraden els enigmes manuals, però les tisores estan desactivades. Gairebé tots necessiten retallar.',
    'warning.no_scissors': 'Sense tisores, l’agent té menys tipus d’enigma entre els quals triar.',
    'warning.short_expert':
      'Enigmes de nivell expert en una partida molt curta deixen lloc per a molt pocs. Prova una partida més llarga o un nivell més fàcil.',
    'warning.many_players_no_game_master':
      'Més de 8 jugadors és un grup gran. Un director de joc ajuda a fer que ningú no es perdi.',
    'warning.envelopes_without_envelopes':
      'El joc fa servir sobres, però no en tens. Pots doblegar un paper i tancar-lo amb un adhesiu.',
    'warning.no_help': 'No hi ha pistes ni comprovació de respostes. Qui s’encalli no podrà demanar ajuda.',
    'warning.all_puzzles_avoided':
      'Evites tots els tipus d’enigma. Aleshores l’agent tria pel seu compte. Marca almenys un tipus com a «Normal».',
    'warning.more_names_than_players': 'Has posat més noms que jugadors. L’agent fa servir els {count} primers noms.',

    'action.download': 'Baixa la configuració',
    'action.load': 'Carrega una configuració',
    'action.copy_prompt': 'Copia la instrucció',
    'action.reset': 'Torna a començar',
    'action.undo': 'Desfés',
    'action.show_summary': 'Revisa i desa',
    'load.hint': 'També pots deixar anar un fitxer .mystery-config.json a qualsevol lloc de la pàgina.',
    'drop.title': 'Deixa anar aquí el teu fitxer de configuració',

    'status.downloaded': 'S’ha desat {fileName}. Busca’l a la teva carpeta de Baixades.',
    'status.copied': 'Instrucció copiada. Enganxa-la al teu agent.',
    'status.copy_failed': 'Aquí no s’ha pogut copiar. Selecciona el text del quadre de sota i copia’l.',
    'status.loaded': 'S’ha carregat {fileName}.',
    'status.load_failed': '{fileName} no és una configuració vàlida de Mystery Forge. No ha canviat res.',
    'status.reset': 'Totes les opcions han tornat al principi.',
    'status.draft_restored': 'Hem recuperat el teu últim esborrany.',
    'status.preset_applied': 'Preparat per a «{audience}». Pots canviar qualsevol opció a sota.',
    'note.language_followed':
      'El joc segueix l’idioma de la pàgina. Idioma del joc: {language}. Paper: {paper}. Pots canviar tots dos a sota.',

    'error.json': 'El fitxer no conté un text JSON vàlid.',
    'error.whole_file': 'El fitxer',
    'error.required': '{field}: falta aquest valor.',
    'error.additionalProperties': '{field}: aquest ajust no existeix.',
    'error.type': '{field}: el valor no és del tipus correcte.',
    'error.enum': '{field}: aquesta opció no està permesa.',
    'error.minimum': '{field}: el valor ha de ser {limit} o més.',
    'error.maximum': '{field}: el valor ha de ser {limit} o menys.',
    'error.maxLength': '{field}: el text ha de tenir {limit} caràcters o menys.',
    'error.maxItems': '{field}: la llista ha de tenir {limit} elements o menys.',

    'prompt.title': 'Altres aplicacions d’agents',
    'prompt.help':
      'Fas servir una altra aplicació d’agents en lloc de Claude Code? Copia aquesta instrucció i enganxa-la allà.',
    'prompt.intro': 'Crea un joc de misteri per imprimir amb Mystery Forge.',
    'prompt.run_skill':
      'Executa la skill create-game amb la configuració de sota. Tracta-la com el fitxer de configuració {fileName}. No la canviïs.',
    'prompt.questions': 'Pregunta’m només el que pregunti la skill.',

    'next.title': 'Passos següents',
    'next.install':
      'Instal·la uv (una petita eina que executa programes de Python) i Claude Code (l’agent d’IA que escriu el joc). Només cal fer-ho una vegada.',
    'next.link_uv': 'Instal·la uv',
    'next.link_claude': 'Instal·la Claude Code',
    'next.open': 'Obre la carpeta «generator» d’aquest projecte a Claude Code:',
    'next.windows_label': 'Windows:',
    'next.windows':
      'a l’Explorador de fitxers, obre la carpeta. Escriu cmd a la barra d’adreces i prem Retorn. Després escriu claude i prem Retorn.',
    'next.mac_label': 'macOS:',
    'next.mac':
      'al Finder, fes clic amb el botó dret a la carpeta i tria «Nou terminal a la carpeta» (a Serveis). Després escriu claude i prem Retorn.',
    'next.trust': 'Quan Claude Code et pregunti si confies en la carpeta, digues que sí.',
    'next.say': 'Escriu «crea un joc». L’agent troba {fileName} a la teva carpeta de Baixades.',
    'next.note':
      'El procés triga {time}. Queda’t per a les primeres preguntes. Quan hagis triat el concepte de la història, ja te’n pots anar.',

    'field.schema_version.label': 'Versió de la configuració',
    'field.schema_version.help': 'La versió del format de configuració. La pàgina la posa per tu.',
    'enum.schema_version.1.label': 'Versió 1',
    'enum.schema_version.1.help': 'El format de configuració actual.',

    'field.audience.label': 'Grup',
    'field.audience.help': 'Qui seu a la taula. El grup ajusta la dificultat, la lectura i el to.',
    'enum.audience.kids.label': 'Infants',
    'enum.audience.kids.help': 'De 7 a 11 anys. Textos curts, història amable i lletra gran.',
    'enum.audience.family.label': 'Família',
    'enum.audience.family.help': 'Petits i grans junts. Divertit per a totes les edats.',
    'enum.audience.teens.label': 'Adolescents',
    'enum.audience.teens.help': 'De 12 a 17 anys. Més misteri i una mica més de repte.',
    'enum.audience.adults.label': 'Adults',
    'enum.audience.adults.help': 'Un sopar amb amics o una nit de jocs. Es permeten trames més fosques.',
    'enum.audience.puzzle_fans.label': 'Fans dels enigmes',
    'enum.audience.puzzle_fans.help': 'Gent que adora les sales d’escapada. Enigmes difícils i menys història.',

    'field.format.label': 'Format',
    'field.format.help': 'Com avancen els jugadors pel joc.',
    'enum.format.envelopes.label': 'Obrir sobres d’un en un',
    'enum.format.envelopes.help': 'Cada enigma resolt et diu quin sobre has d’obrir després.',
    'enum.format.case_file.label': 'Llegir un expedient i acusar un sospitós',
    'enum.format.case_file.help': 'Estudia les pistes, troba el culpable i demostra-ho.',
    'enum.format.both.label': 'Totes dues coses (recomanat)',
    'enum.format.both.help': 'Els sobres revelen l’expedient pas a pas. L’experiència més completa.',

    'field.players.label': 'Jugadors',
    'field.players.help': 'Les persones que juguen.',
    'field.players.count.label': 'Nombre de jugadors',
    'field.players.count.help': 'D’1 a 12. Amb més jugadors hi ha més enigmes alhora.',
    'field.players.names.label': 'Noms dels jugadors',
    'field.players.names.help': 'L’agent pot posar els noms a les fitxes de personatge i a la història.',

    'field.host.label': 'Qui dirigeix el joc',
    'field.host.help': 'L’amfitrió és la persona que imprimeix i prepara el joc.',
    'enum.host.self_running.label': 'El joc es dirigeix sol',
    'enum.host.self_running.help': 'Tothom juga. Les pàgines us diuen què heu de fer després.',
    'enum.host.host_plays.label': 'L’amfitrió també juga',
    'enum.host.host_plays.help': 'L’amfitrió prepara la taula i després juga com els altres.',
    'enum.host.game_master.label': 'Un director de joc',
    'enum.host.game_master.help': 'L’amfitrió coneix la solució, llegeix la història en veu alta i dona pistes.',

    'field.duration_minutes.label': 'Temps de joc',
    'field.duration_minutes.help': 'El que dura la partida a la taula, de 30 minuts a 4 hores.',

    'field.difficulty.label': 'Dificultat',
    'field.difficulty.help': 'Com són de difícils els enigmes.',
    'enum.difficulty.easy.label': 'Fàcil',
    'enum.difficulty.easy.help': 'Pistes clares. Ideal per a qui hi juga per primera vegada.',
    'enum.difficulty.medium.label': 'Mitjana',
    'enum.difficulty.medium.help': 'Cal pensar una mica. Ideal per a gairebé tots els grups.',
    'enum.difficulty.hard.label': 'Difícil',
    'enum.difficulty.hard.help': 'Les pistes s’amaguen bé. Per a grups que hi juguen sovint.',
    'enum.difficulty.expert.label': 'Experta',
    'enum.difficulty.expert.help': 'Poques pistes i molts passos. Per als amants dels enigmes.',

    'field.language.label': 'Idioma del joc',
    'field.language.help': 'L’idioma de totes les pàgines impreses.',
    'enum.language.en.label': 'Anglès',
    'enum.language.en.help': 'Totes les pàgines en anglès.',
    'enum.language.es.label': 'Castellà',
    'enum.language.es.help': 'Totes les pàgines en castellà.',
    'enum.language.ca.label': 'Català',
    'enum.language.ca.help': 'Totes les pàgines en català.',
    'enum.language.fr.label': 'Francès',
    'enum.language.fr.help': 'Totes les pàgines en francès.',
    'enum.language.de.label': 'Alemany',
    'enum.language.de.help': 'Totes les pàgines en alemany.',
    'enum.language.it.label': 'Italià',
    'enum.language.it.help': 'Totes les pàgines en italià.',
    'enum.language.pt.label': 'Portuguès',
    'enum.language.pt.help': 'Totes les pàgines en portuguès.',
    'enum.language.af.label': 'Afrikaans',
    'enum.language.af.help': 'Totes les pàgines en afrikaans.',
    'enum.language.ar.label': 'Àrab',
    'enum.language.ar.help': 'Totes les pàgines en àrab.',
    'enum.language.bg.label': 'Búlgar',
    'enum.language.bg.help': 'Totes les pàgines en búlgar.',
    'enum.language.bn.label': 'Bengalí',
    'enum.language.bn.help': 'Totes les pàgines en bengalí.',
    'enum.language.cs.label': 'Txec',
    'enum.language.cs.help': 'Totes les pàgines en txec.',
    'enum.language.cy.label': 'Gal·lès',
    'enum.language.cy.help': 'Totes les pàgines en gal·lès.',
    'enum.language.da.label': 'Danès',
    'enum.language.da.help': 'Totes les pàgines en danès.',
    'enum.language.el.label': 'Grec',
    'enum.language.el.help': 'Totes les pàgines en grec.',
    'enum.language.et.label': 'Estonià',
    'enum.language.et.help': 'Totes les pàgines en estonià.',
    'enum.language.eu.label': 'Basc',
    'enum.language.eu.help': 'Totes les pàgines en basc.',
    'enum.language.fa.label': 'Persa',
    'enum.language.fa.help': 'Totes les pàgines en persa.',
    'enum.language.fi.label': 'Finès',
    'enum.language.fi.help': 'Totes les pàgines en finès.',
    'enum.language.ga.label': 'Irlandès',
    'enum.language.ga.help': 'Totes les pàgines en irlandès.',
    'enum.language.gl.label': 'Gallec',
    'enum.language.gl.help': 'Totes les pàgines en gallec.',
    'enum.language.he.label': 'Hebreu',
    'enum.language.he.help': 'Totes les pàgines en hebreu.',
    'enum.language.hi.label': 'Hindi',
    'enum.language.hi.help': 'Totes les pàgines en hindi.',
    'enum.language.hr.label': 'Croat',
    'enum.language.hr.help': 'Totes les pàgines en croat.',
    'enum.language.hu.label': 'Hongarès',
    'enum.language.hu.help': 'Totes les pàgines en hongarès.',
    'enum.language.id.label': 'Indonesi',
    'enum.language.id.help': 'Totes les pàgines en indonesi.',
    'enum.language.is.label': 'Islandès',
    'enum.language.is.help': 'Totes les pàgines en islandès.',
    'enum.language.ja.label': 'Japonès',
    'enum.language.ja.help': 'Totes les pàgines en japonès.',
    'enum.language.ko.label': 'Coreà',
    'enum.language.ko.help': 'Totes les pàgines en coreà.',
    'enum.language.lt.label': 'Lituà',
    'enum.language.lt.help': 'Totes les pàgines en lituà.',
    'enum.language.lv.label': 'Letó',
    'enum.language.lv.help': 'Totes les pàgines en letó.',
    'enum.language.ms.label': 'Malai',
    'enum.language.ms.help': 'Totes les pàgines en malai.',
    'enum.language.nb.label': 'Noruec',
    'enum.language.nb.help': 'Totes les pàgines en noruec.',
    'enum.language.nl.label': 'Neerlandès',
    'enum.language.nl.help': 'Totes les pàgines en neerlandès.',
    'enum.language.pl.label': 'Polonès',
    'enum.language.pl.help': 'Totes les pàgines en polonès.',
    'enum.language.ro.label': 'Romanès',
    'enum.language.ro.help': 'Totes les pàgines en romanès.',
    'enum.language.ru.label': 'Rus',
    'enum.language.ru.help': 'Totes les pàgines en rus.',
    'enum.language.sk.label': 'Eslovac',
    'enum.language.sk.help': 'Totes les pàgines en eslovac.',
    'enum.language.sl.label': 'Eslovè',
    'enum.language.sl.help': 'Totes les pàgines en eslovè.',
    'enum.language.sr.label': 'Serbi',
    'enum.language.sr.help': 'Totes les pàgines en serbi.',
    'enum.language.sv.label': 'Suec',
    'enum.language.sv.help': 'Totes les pàgines en suec.',
    'enum.language.sw.label': 'Suahili',
    'enum.language.sw.help': 'Totes les pàgines en suahili.',
    'enum.language.ta.label': 'Tàmil',
    'enum.language.ta.help': 'Totes les pàgines en tàmil.',
    'enum.language.th.label': 'Tai',
    'enum.language.th.help': 'Totes les pàgines en tai.',
    'enum.language.tl.label': 'Filipí',
    'enum.language.tl.help': 'Totes les pàgines en filipí.',
    'enum.language.tr.label': 'Turc',
    'enum.language.tr.help': 'Totes les pàgines en turc.',
    'enum.language.uk.label': 'Ucraïnès',
    'enum.language.uk.help': 'Totes les pàgines en ucraïnès.',
    'enum.language.ur.label': 'Urdú',
    'enum.language.ur.help': 'Totes les pàgines en urdú.',
    'enum.language.vi.label': 'Vietnamita',
    'enum.language.vi.help': 'Totes les pàgines en vietnamita.',
    'enum.language.zh.label': 'Xinès',
    'enum.language.zh.help': 'Totes les pàgines en xinès.',

    'field.theme.label': 'Història',
    'field.theme.help': 'La idea de la història i el seu to.',
    'field.theme.idea.label': 'Idea per a la història',
    'field.theme.idea.help':
      'Unes quantes paraules o unes quantes línies. Llocs, personatges i un crim hi ajuden molt.',
    'field.theme.tone.label': 'To',
    'field.theme.tone.help': 'Quina sensació transmet la història.',
    'enum.theme.tone.surprise.label': 'Sorprèn-me',
    'enum.theme.tone.surprise.help': 'L’agent tria el to que encaixa amb la idea.',
    'enum.theme.tone.cozy.label': 'Acollidor',
    'enum.theme.tone.cozy.help': 'Càlid i lleuger, com un misteri de poble.',
    'enum.theme.tone.adventure.label': 'Aventura',
    'enum.theme.tone.adventure.help': 'Mapes, tresors i una cursa contra rellotge.',
    'enum.theme.tone.noir.label': 'Negre',
    'enum.theme.tone.noir.help': 'Carrers amb pluja, secrets i un detectiu cansat.',
    'enum.theme.tone.spooky.label': 'Inquietant',
    'enum.theme.tone.spooky.help': 'Portes que grinyolen i ombres estranyes.',
    'enum.theme.tone.comedic.label': 'Divertit',
    'enum.theme.tone.comedic.help': 'Sospitosos absurds i moltes bromes.',
    'enum.theme.tone.dramatic.label': 'Dramàtic',
    'enum.theme.tone.dramatic.help': 'Molt en joc, traïcions i grans revelacions.',
    'field.theme.era.label': 'Època',
    'field.theme.era.help': 'Quan passa la història.',
    'enum.theme.era.any.label': 'Qualsevol',
    'enum.theme.era.any.help': 'L’agent tria l’època que encaixa amb la idea.',
    'enum.theme.era.historical.label': 'El passat',
    'enum.theme.era.historical.help': 'Castells, trens de vapor o els feliços anys vint.',
    'enum.theme.era.modern.label': 'Avui',
    'enum.theme.era.modern.help': 'Mòbils, oficines i ciutats modernes.',
    'enum.theme.era.future.label': 'El futur',
    'enum.theme.era.future.help': 'Estacions espacials, robots i tecnologia nova.',
    'enum.theme.era.fantasy.label': 'Fantasia',
    'enum.theme.era.fantasy.help': 'Màgia, dracs i mons inventats.',

    'field.content.label': 'Contingut',
    'field.content.help': 'Límits sobre el que pot contenir la història.',
    'field.content.death_allowed.label': 'Una mort a la història',
    'field.content.death_allowed.help':
      'Activat permet un assassinat clàssic. Desactivat deixa el crim en un robatori o un enigma.',
    'field.content.scary_level.label': 'Nivell de por',
    'field.content.scary_level.help': 'Quanta por pot fer la història.',
    'enum.content.scary_level.none.label': 'Gens',
    'enum.content.scary_level.none.help': 'Res que faci por.',
    'enum.content.scary_level.mild.label': 'Una mica',
    'enum.content.scary_level.mild.help': 'Alguna esgarrifança de tant en tant.',
    'enum.content.scary_level.spooky.label': 'Terror',
    'enum.content.scary_level.spooky.help': 'Ambient d’autèntica història de fantasmes.',
    'field.content.reading_load.label': 'Lectura',
    'field.content.reading_load.help': 'Quant de text llegeixen els jugadors.',
    'enum.content.reading_load.light.label': 'Lleugera',
    'enum.content.reading_load.light.help': 'Textos curts. Ideal per a infants i grups grans.',
    'enum.content.reading_load.medium.label': 'Mitjana',
    'enum.content.reading_load.medium.help': 'Cartes i notes d’una pàgina, més o menys.',
    'enum.content.reading_load.heavy.label': 'Abundant',
    'enum.content.reading_load.heavy.help': 'Diaris, informes i cartes llargues plenes de pistes.',

    'field.personalization.label': 'Tocs personals',
    'field.personalization.help': 'Detalls personals que inclou la història.',
    'field.personalization.host_name.label': 'Nom de l’amfitrió',
    'field.personalization.host_name.help': 'La història pot anomenar l’amfitrió.',
    'field.personalization.place.label': 'Lloc',
    'field.personalization.place.help': 'On jugueu. La història pot passar allà.',
    'field.personalization.inside_jokes.label': 'Bromes internes',
    'field.personalization.inside_jokes.help': 'Bromes o referències curtes que coneix el teu grup. Fins a 5.',
    'field.personalization.dedication.label': 'Dedicatòria',
    'field.personalization.dedication.help': 'Una línia per a la portada, per exemple per a un aniversari.',

    'field.puzzle_preferences.label': 'Tipus d’enigma',
    'field.puzzle_preferences.help': 'Quant agrada als jugadors cada tipus d’enigma.',
    'field.puzzle_preferences.words.label': 'Paraules',
    'field.puzzle_preferences.words.help': 'Anagrames, xifratges i missatges amagats.',
    'field.puzzle_preferences.numbers.label': 'Nombres',
    'field.puzzle_preferences.numbers.help': 'Codis de cadenat, sumes i dates.',
    'field.puzzle_preferences.logic.label': 'Lògica',
    'field.puzzle_preferences.logic.help': 'Taules de pistes: qui seia on, qui té què.',
    'field.puzzle_preferences.visual.label': 'Visuals',
    'field.puzzle_preferences.visual.help': 'Detalls amagats en dibuixos, mapes i símbols.',
    'field.puzzle_preferences.crafts.label': 'Manualitats',
    'field.puzzle_preferences.crafts.help': 'Doblegar, retallar i mirar pàgines a contrallum.',
    'field.puzzle_preferences.deduction.label': 'Deducció',
    'field.puzzle_preferences.deduction.help': 'Descobrir qui menteix, comparar coartades i veure l’error.',
    ...preferenceChoices('words', CATALAN_PREFERENCE),
    ...preferenceChoices('numbers', CATALAN_PREFERENCE),
    ...preferenceChoices('logic', CATALAN_PREFERENCE),
    ...preferenceChoices('visual', CATALAN_PREFERENCE),
    ...preferenceChoices('crafts', CATALAN_PREFERENCE),
    ...preferenceChoices('deduction', CATALAN_PREFERENCE),

    'field.equipment.label': 'Material',
    'field.equipment.help': 'El que tens per imprimir i muntar el joc.',
    'field.equipment.printer.label': 'Impressora',
    'field.equipment.printer.help': 'L’agent tria colors que s’hi imprimeixin bé.',
    'enum.equipment.printer.color.label': 'Color',
    'enum.equipment.printer.color.help': 'Pàgines a tot color.',
    'enum.equipment.printer.black_and_white.label': 'Blanc i negre',
    'enum.equipment.printer.black_and_white.help': 'Les pàgines fan servir només negre i tons de gris.',
    'field.equipment.ink_saving.label': 'Estalviar tinta',
    'field.equipment.ink_saving.help': 'Fons clars que gasten menys tinta.',
    'field.equipment.paper.label': 'Mida del paper',
    'field.equipment.paper.help': 'El paper de la teva impressora.',
    'enum.equipment.paper.A4.label': 'A4',
    'enum.equipment.paper.A4.help': 'La mida habitual a Europa i a gairebé tot el món.',
    'enum.equipment.paper.Letter.label': 'Carta',
    'enum.equipment.paper.Letter.help': 'La mida habitual als Estats Units i al Canadà.',
    'field.equipment.scissors.label': 'Tisores',
    'field.equipment.scissors.help': 'Els jugadors poden retallar paper.',
    'field.equipment.tape_or_glue.label': 'Cinta adhesiva o cola',
    'field.equipment.tape_or_glue.help': 'Els jugadors poden enganxar peces.',
    'field.equipment.envelopes.label': 'Sobres',
    'field.equipment.envelopes.help': 'Tens sobres per amagar les parts següents del joc.',

    'field.assistance.label': 'Ajuda',
    'field.assistance.help': 'Ajuda per als jugadors durant el joc.',
    'field.assistance.hints.label': 'Pistes',
    'field.assistance.hints.help': 'Petites empentes per a cada enigma, d’una en una.',
    'field.assistance.paper_answer_check.label': 'Comprovació en paper',
    'field.assistance.paper_answer_check.help': 'Una pàgina impresa per comprovar respostes sense cap aparell.',
    'field.assistance.companion_page.label': 'Pàgina de suport',
    'field.assistance.companion_page.help':
      'Una pàgina per al mòbil o l’ordinador que comprova respostes i dona pistes.',

    'field.visuals.label': 'Aspecte',
    'field.visuals.help': 'L’aspecte de les pàgines impreses.',
    'field.visuals.style.label': 'Estil',
    'field.visuals.style.help': 'Els colors, les lletres i els ornaments de les pàgines.',
    'enum.visuals.style.auto.label': 'Automàtic',
    'enum.visuals.style.auto.help': 'L’agent tria l’estil que encaixa amb la història.',
    'enum.visuals.style.vintage.label': 'Antic',
    'enum.visuals.style.vintage.help': 'Paper vell, lletra de màquina d’escriure i segells.',
    'enum.visuals.style.noir.label': 'Negre',
    'enum.visuals.style.noir.help': 'Blanc, negre i un toc de vermell.',
    'enum.visuals.style.modern.label': 'Modern',
    'enum.visuals.style.modern.help': 'Pàgines netes, com un informe policial d’avui.',
    'enum.visuals.style.victorian.label': 'Victorià',
    'enum.visuals.style.victorian.help': 'Marcs recarregats i lletres elegants.',
    'enum.visuals.style.scifi.label': 'Ciència-ficció',
    'enum.visuals.style.scifi.help': 'Pantalles, quadrícules i colors lluminosos.',
    'enum.visuals.style.fantasy.label': 'Fantasia',
    'enum.visuals.style.fantasy.help': 'Pergamí, runes i mapes antics.',
    'enum.visuals.style.kids.label': 'Infantil',
    'enum.visuals.style.kids.help': 'Colors vius i formes rodones i amables.',
    'enum.visuals.style.minimal.label': 'Minimalista',
    'enum.visuals.style.minimal.help': 'Pàgines senzilles que s’imprimeixen ràpid i netes.',
    'field.visuals.images.label': 'Imatges',
    'field.visuals.images.help': 'Dibuixos a les pàgines.',
    'enum.visuals.images.svg.label': 'Dibuixos',
    'enum.visuals.images.svg.help': 'Dibuixos senzills que l’agent crea per a la història.',
    'enum.visuals.images.none.label': 'Sense imatges',
    'enum.visuals.images.none.help': 'Només text. Més ràpid de crear i d’imprimir.',
    'field.visuals.readable_font.label': 'Lletra fàcil de llegir',
    'field.visuals.readable_font.help': 'Una lletra gran i senzilla. Ideal per a infants i per a ulls cansats.',

    'field.generation.label': 'Generació',
    'field.generation.help': 'Com treballa l’agent.',
    'field.generation.quality.label': 'Qualitat',
    'field.generation.quality.help': 'La millor triga més, però surten menys enigmes trencats.',
    'enum.generation.quality.fast.label': 'Ràpida',
    'enum.generation.quality.fast.help': 'Més ràpida, amb menys comprovacions. Ideal per a una prova ràpida.',
    'enum.generation.quality.best.label': 'La millor',
    'enum.generation.quality.best.help':
      'Menys enigmes trencats: més jugadors de prova amb IA intenten resoldre cada enigma.',
    'field.generation.pick_concept.label': 'Concepte de la història',
    'field.generation.pick_concept.help': 'Primer l’agent escriu uns quants conceptes d’història.',
    'enum.generation.pick_concept.ask.label': 'Vull triar',
    'enum.generation.pick_concept.ask.help': 'L’agent t’ensenya els conceptes i tu en tries un.',
    'enum.generation.pick_concept.agent.label': 'Que triï l’agent',
    'enum.generation.pick_concept.agent.help': 'L’agent en tria un. La història també serà una sorpresa per a tu.',
    'field.generation.seed.label': 'Llavor',
    'field.generation.seed.help': 'Un nombre que fa repetibles les eleccions a l’atzar. 0 vol dir una llavor nova.',

    'field.output.label': 'Sortida',
    'field.output.help': 'On desa l’agent el joc acabat.',
    'field.output.folder.label': 'Carpeta de sortida',
    'field.output.folder.help': 'La carpeta per al joc acabat. Buit vol dir el teu Escriptori.',
  };

  /** @type {Record<MysteryForgeUiLanguage, Record<string, string>>} */
  const TEXTS = { en, es, ca };

  /**
   * Return the text of a key in a language, with each {name} placeholder filled from `params`. An unknown language
   * falls back to English, and an unknown key returns the key itself, so a gap shows on the page instead of a crash.
   * @param {string} language
   * @param {string} key
   * @param {Record<string, string | number>} [params]
   * @returns {string}
   */
  function translate(language, key, params = {}) {
    const texts = TEXTS[/** @type {MysteryForgeUiLanguage} */ (language)] ?? en;
    const template = texts[key] ?? key;
    return template.replace(/\{(\w+)\}/g, (placeholder, name) => (name in params ? String(params[name]) : placeholder));
  }

  /**
   * Return the first browser language that the page supports, else English.
   * @param {readonly string[]} browserLanguages
   * @returns {MysteryForgeUiLanguage}
   */
  function pickUiLanguage(browserLanguages) {
    for (const browserLanguage of browserLanguages) {
      const base = browserLanguage.toLowerCase().split('-')[0];
      const match = UI_LANGUAGES.find((language) => language === base);
      if (match) {
        return match;
      }
    }
    return 'en';
  }

  /**
   * Return the keys that each language must define: a label and a help text for each property path of the schema,
   * and for each enum value.
   * @param {MysteryForgeJsonSchema} schema
   * @returns {string[]}
   */
  function requiredSchemaTextKeys(schema) {
    /** @type {string[]} */
    const keys = [];
    /**
     * @param {MysteryForgeJsonSchema} node
     * @param {string} prefix
     */
    function visit(node, prefix) {
      for (const [name, child] of Object.entries(node.properties ?? {})) {
        const fieldPath = prefix ? `${prefix}.${name}` : name;
        keys.push(`field.${fieldPath}.label`, `field.${fieldPath}.help`);
        for (const value of child.enum ?? []) {
          keys.push(`enum.${fieldPath}.${String(value)}.label`, `enum.${fieldPath}.${String(value)}.help`);
        }
        visit(child, fieldPath);
      }
    }
    visit(schema, '');
    return keys;
  }

  globalThis.MysteryForgeUiText = { UI_LANGUAGES, TEXTS, translate, pickUiLanguage, requiredSchemaTextKeys };
})();
